name: Test

on:
  push:
    branches:
      - "**"
      - "!main"
      - "!master"

jobs:
  test:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: test
        run: just test

